project:
  type: website
  output-dir: docs

website:
  title: "Jess Rousselle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Project.qmd
      - href: free.qmd
        text: Favorite Media
      - resume.qmd


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

