project:
  type: website
  output-dir: docs

website:
  title: "Jess Rousselle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
     # - href: about.qmd
     #   text: About Me
      - Project.qmd
     # - href: free.qmd
     #   text: Favorite Media

format:
  html:
    theme: 
      - flatly
      - styles.scss
    mainfont: Yrsa
    toc: true
    page-layout: full

editor: visual

